insert into public.item_assignments (normalized_text, category, emoji, confidence, source)
values
  ('2% milk', 'dairy', '🥛', 0.95, 'seed_v1'),
  ('acorn squash', 'produce', '🥬', 0.95, 'seed_v1'),
  ('active dry yeast', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('aftershave', 'personal_care', '🧴', 0.95, 'seed_v1'),
  ('agave syrup', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('aioli', 'condiment', '🧂', 0.95, 'seed_v1'),
  ('air freshener', 'household', '🧻', 0.95, 'seed_v1'),
  ('ale', 'alcohol', '🍷', 0.95, 'seed_v1'),
  ('all-purpose cleaner', 'household', '🧻', 0.95, 'seed_v1'),
  ('all-purpose flour', 'grain', '🌾', 0.95, 'seed_v1'),
  ('allspice', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('almond', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('almond butter', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('almond extract', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('almond milk', 'dairy', '🥛', 0.95, 'seed_v1'),
  ('aluminum foil', 'household', '🧻', 0.95, 'seed_v1'),
  ('anchovy', 'seafood', '🐟', 0.95, 'seed_v1'),
  ('angel hair', 'pasta', '🍝', 0.95, 'seed_v1'),
  ('apple', 'produce', '🍎', 0.95, 'seed_v1'),
  ('apple cider', 'produce', '🍎', 0.95, 'seed_v1'),
  ('apple cider vinegar', 'pantry', '🍎', 0.95, 'seed_v1'),
  ('apple juice', 'beverage', '🧃', 0.95, 'seed_v1'),
  ('apple sauce', 'produce', '🍎', 0.95, 'seed_v1'),
  ('apricot', 'produce', '🥬', 0.95, 'seed_v1'),
  ('arborio rice', 'grain', '🍚', 0.95, 'seed_v1'),
  ('artichoke', 'produce', '🥬', 0.95, 'seed_v1'),
  ('artichoke dip', 'deli', '🥪', 0.95, 'seed_v1'),
  ('artichoke heart', 'produce', '🥬', 0.95, 'seed_v1'),
  ('arugula', 'produce', '🥬', 0.95, 'seed_v1'),
  ('asparagus', 'produce', '🥬', 0.95, 'seed_v1'),
  ('avocado oil', 'pantry', '🥑', 0.95, 'seed_v1'),
  ('baby bottle', 'baby', '🍼', 0.95, 'seed_v1'),
  ('baby carrot', 'produce', '🥬', 0.95, 'seed_v1'),
  ('baby cereal', 'baby', '🍼', 0.95, 'seed_v1'),
  ('baby food', 'baby', '🍼', 0.95, 'seed_v1'),
  ('baby formula powder', 'baby', '🍼', 0.95, 'seed_v1'),
  ('baby lotion', 'baby', '🧴', 0.95, 'seed_v1'),
  ('baby potato', 'produce', '🥔', 0.95, 'seed_v1'),
  ('baby puree', 'baby', '🍼', 0.95, 'seed_v1'),
  ('baby shampoo', 'baby', '🧴', 0.95, 'seed_v1'),
  ('baby snack', 'baby', '🍼', 0.95, 'seed_v1'),
  ('baby spinach', 'produce', '🥬', 0.95, 'seed_v1'),
  ('baby wipe', 'baby', '🍼', 0.95, 'seed_v1'),
  ('bacon', 'meat', '🥓', 0.95, 'seed_v1'),
  ('bagel', 'bakery', '🥯', 0.95, 'seed_v1'),
  ('bagel thin', 'bakery', '🥯', 0.95, 'seed_v1'),
  ('baguette', 'bakery', '🍞', 0.95, 'seed_v1'),
  ('baked bean', 'canned', '🥫', 0.95, 'seed_v1'),
  ('baking chocolate', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('baking cocoa', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('baking flour', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('baking paper', 'baking', '🧁', 0.95, 'seed_v1'),
  ('baking powder', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('baking soda', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('baking tray', 'baking', '🧁', 0.95, 'seed_v1'),
  ('baking yeast', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('balsamic vinegar', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('bamboo shoot', 'produce', '🥬', 0.95, 'seed_v1'),
  ('banana', 'produce', '🍌', 0.95, 'seed_v1'),
  ('banana chip', 'produce', '🍌', 0.95, 'seed_v1'),
  ('bar soap', 'personal_care', '🧼', 0.95, 'seed_v1'),
  ('barley', 'grain', '🌾', 0.95, 'seed_v1'),
  ('basil', 'produce', '🥬', 0.95, 'seed_v1'),
  ('basil dried', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('basmati rice', 'grain', '🍚', 0.95, 'seed_v1'),
  ('battery', 'household', '🧻', 0.95, 'seed_v1'),
  ('bay leaf', 'produce', '🥬', 0.95, 'seed_v1'),
  ('bbq sauce', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('bean sprout', 'produce', '🥬', 0.95, 'seed_v1'),
  ('beef', 'meat', '🥩', 0.95, 'seed_v1'),
  ('beef bouillon', 'pantry', '🥩', 0.95, 'seed_v1'),
  ('beef chuck', 'meat', '🥩', 0.95, 'seed_v1'),
  ('beef jerky', 'snack', '🥩', 0.95, 'seed_v1'),
  ('beef mince', 'meat', '🥩', 0.95, 'seed_v1'),
  ('beef patty', 'meat', '🥩', 0.95, 'seed_v1'),
  ('beef roast', 'meat', '🥩', 0.95, 'seed_v1'),
  ('beef stew meat', 'meat', '🥩', 0.95, 'seed_v1'),
  ('beer', 'alcohol', '🍺', 0.95, 'seed_v1'),
  ('beet', 'produce', '🥬', 0.95, 'seed_v1'),
  ('beetroot', 'produce', '🥬', 0.95, 'seed_v1'),
  ('bell pepper', 'produce', '🫑', 0.95, 'seed_v1'),
  ('bin bag', 'household', '🧻', 0.95, 'seed_v1'),
  ('bin liner', 'household', '🧻', 0.95, 'seed_v1'),
  ('bird seed', 'pet', '🐾', 0.95, 'seed_v1'),
  ('biscuit', 'snack', '🍿', 0.95, 'seed_v1'),
  ('black bean', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('black pepper', 'pantry', '🫑', 0.95, 'seed_v1'),
  ('black tea', 'beverage', '🍵', 0.95, 'seed_v1'),
  ('black tea bag', 'pantry', '🍵', 0.95, 'seed_v1'),
  ('blackberry', 'produce', '🫐', 0.95, 'seed_v1'),
  ('bleach', 'household', '🧻', 0.95, 'seed_v1'),
  ('blood orange', 'produce', '🍊', 0.95, 'seed_v1'),
  ('blue cheese', 'dairy', '🧀', 0.95, 'seed_v1'),
  ('blueberry', 'produce', '🫐', 0.95, 'seed_v1'),
  ('body lotion', 'personal_care', '🧴', 0.95, 'seed_v1'),
  ('body scrub', 'personal_care', '🧴', 0.95, 'seed_v1'),
  ('body wash', 'personal_care', '🧴', 0.95, 'seed_v1'),
  ('bok choy', 'produce', '🥬', 0.95, 'seed_v1'),
  ('bologna', 'meat', '🍗', 0.95, 'seed_v1'),
  ('bouillon cube', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('bran cereal', 'grain', '🌾', 0.95, 'seed_v1'),
  ('brazil nut', 'nut_seed', '🥜', 0.95, 'seed_v1'),
  ('bread', 'bakery', '🍞', 0.95, 'seed_v1'),
  ('bread flour', 'grain', '🍞', 0.95, 'seed_v1'),
  ('bread improver', 'pantry', '🍞', 0.95, 'seed_v1'),
  ('bread roll', 'bakery', '🍞', 0.95, 'seed_v1'),
  ('breadcrumbs', 'grain', '🍞', 0.95, 'seed_v1'),
  ('breadcrumbs italian', 'pantry', '🍞', 0.95, 'seed_v1'),
  ('breadcrumbs seasoned', 'pantry', '🍞', 0.95, 'seed_v1'),
  ('breadstick', 'bakery', '🍞', 0.95, 'seed_v1'),
  ('breakfast burrito', 'breakfast', '🥣', 0.95, 'seed_v1'),
  ('breakfast sandwich', 'breakfast', '🥣', 0.95, 'seed_v1'),
  ('breakfast sausage', 'meat', '🌭', 0.95, 'seed_v1'),
  ('brie', 'dairy', '🧀', 0.95, 'seed_v1'),
  ('brioche', 'bakery', '🍞', 0.95, 'seed_v1'),
  ('brisket', 'meat', '🍗', 0.95, 'seed_v1'),
  ('broccoli', 'produce', '🥦', 0.95, 'seed_v1'),
  ('broccolini', 'produce', '🥦', 0.95, 'seed_v1'),
  ('brown rice', 'grain', '🍚', 0.95, 'seed_v1'),
  ('brown rice packet', 'grain', '🍚', 0.95, 'seed_v1'),
  ('brown sugar', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('brownie', 'bakery', '🍞', 0.95, 'seed_v1'),
  ('brownie mix', 'baking', '🧁', 0.95, 'seed_v1'),
  ('brussels sprout', 'produce', '🥬', 0.95, 'seed_v1'),
  ('bulgur', 'grain', '🌾', 0.95, 'seed_v1'),
  ('bun', 'bakery', '🍞', 0.95, 'seed_v1'),
  ('burger', 'meat', '🍗', 0.95, 'seed_v1'),
  ('butter', 'dairy', '🧈', 0.95, 'seed_v1'),
  ('butter spread', 'dairy', '🧀', 0.95, 'seed_v1'),
  ('buttermilk', 'dairy', '🥛', 0.95, 'seed_v1'),
  ('butternut', 'produce', '🥬', 0.95, 'seed_v1'),
  ('butternut squash', 'produce', '🥬', 0.95, 'seed_v1'),
  ('button mushroom', 'produce', '🥬', 0.95, 'seed_v1'),
  ('cabbage', 'produce', '🥬', 0.95, 'seed_v1'),
  ('cacao nib', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('cajun seasoning', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('cake', 'bakery', '🍞', 0.95, 'seed_v1'),
  ('cake mix', 'baking', '🧁', 0.95, 'seed_v1'),
  ('calamari', 'seafood', '🐟', 0.95, 'seed_v1'),
  ('camembert', 'dairy', '🧀', 0.95, 'seed_v1'),
  ('candle', 'household', '🧻', 0.95, 'seed_v1'),
  ('candy', 'snack', '🍬', 0.95, 'seed_v1'),
  ('canned anchovy', 'canned', '🥫', 0.95, 'seed_v1'),
  ('canned beef broth', 'canned', '🥩', 0.95, 'seed_v1'),
  ('canned black bean', 'canned', '🥫', 0.95, 'seed_v1'),
  ('canned black bean soup', 'canned', '🥫', 0.95, 'seed_v1'),
  ('canned broth', 'canned', '🥫', 0.95, 'seed_v1'),
  ('canned chicken broth', 'canned', '🍗', 0.95, 'seed_v1'),
  ('canned chicken noodle soup', 'canned', '🍗', 0.95, 'seed_v1'),
  ('canned chickpea', 'canned', '🥫', 0.95, 'seed_v1'),
  ('canned chili', 'canned', '🌶️', 0.95, 'seed_v1'),
  ('canned clam chowder', 'canned', '🥫', 0.95, 'seed_v1'),
  ('canned coconut cream', 'canned', '🥛', 0.95, 'seed_v1'),
  ('canned coconut milk', 'canned', '🥛', 0.95, 'seed_v1'),
  ('canned corn', 'canned', '🥫', 0.95, 'seed_v1'),
  ('canned crushed tomato', 'canned', '🍅', 0.95, 'seed_v1'),
  ('canned diced tomato', 'canned', '🍅', 0.95, 'seed_v1'),
  ('canned fruit', 'canned', '🥫', 0.95, 'seed_v1'),
  ('canned green bean', 'canned', '🥫', 0.95, 'seed_v1'),
  ('canned kidney bean', 'canned', '🥫', 0.95, 'seed_v1'),
  ('canned lentil', 'canned', '🥫', 0.95, 'seed_v1'),
  ('canned lentil soup', 'canned', '🥫', 0.95, 'seed_v1'),
  ('canned minestrone', 'canned', '🥫', 0.95, 'seed_v1'),
  ('canned mushroom', 'canned', '🥫', 0.95, 'seed_v1'),
  ('canned pea', 'canned', '🥫', 0.95, 'seed_v1'),
  ('canned pineapple', 'canned', '🍎', 0.95, 'seed_v1'),
  ('canned pumpkin', 'canned', '🥫', 0.95, 'seed_v1'),
  ('canned ravioli', 'canned', '🥫', 0.95, 'seed_v1'),
  ('canned salmon', 'canned', '🐟', 0.95, 'seed_v1'),
  ('canned sardine', 'canned', '🥫', 0.95, 'seed_v1'),
  ('canned soup', 'canned', '🥫', 0.95, 'seed_v1'),
  ('canned stock', 'canned', '🥫', 0.95, 'seed_v1'),
  ('canned tomato', 'canned', '🍅', 0.95, 'seed_v1'),
  ('canned tomato basil soup', 'canned', '🍅', 0.95, 'seed_v1'),
  ('canned tomato puree', 'pantry', '🍅', 0.95, 'seed_v1'),
  ('canned tomato soup', 'canned', '🍅', 0.95, 'seed_v1'),
  ('canned tuna', 'canned', '🐟', 0.95, 'seed_v1'),
  ('canned tuna in oil', 'seafood', '🐟', 0.95, 'seed_v1'),
  ('canned tuna in water', 'seafood', '🐟', 0.95, 'seed_v1'),
  ('canned vegetable broth', 'canned', '🥫', 0.95, 'seed_v1'),
  ('canned whole tomato', 'canned', '🍅', 0.95, 'seed_v1'),
  ('cannellini bean', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('canola oil', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('cantaloupe', 'produce', '🥬', 0.95, 'seed_v1'),
  ('cappelletti', 'pasta', '🍝', 0.95, 'seed_v1'),
  ('cardamom', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('carrot', 'produce', '🥕', 0.95, 'seed_v1'),
  ('cashew', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('cat food', 'pet', '🐱', 0.95, 'seed_v1'),
  ('cat litter', 'pet', '🐾', 0.95, 'seed_v1'),
  ('cat snack', 'pet', '🐾', 0.95, 'seed_v1'),
  ('cat treat', 'pet', '🐾', 0.95, 'seed_v1'),
  ('cauliflower', 'produce', '🥬', 0.95, 'seed_v1'),
  ('cauliflower rice', 'produce', '🍚', 0.95, 'seed_v1'),
  ('cayenne', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('celeriac', 'produce', '🥬', 0.95, 'seed_v1'),
  ('celery', 'produce', '🥬', 0.95, 'seed_v1'),
  ('celery salt', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('celery stick', 'produce', '🥬', 0.95, 'seed_v1'),
  ('cereal', 'grain', '🌾', 0.95, 'seed_v1'),
  ('chai', 'beverage', '🥤', 0.95, 'seed_v1'),
  ('champagne', 'alcohol', '🍾', 0.95, 'seed_v1'),
  ('chard', 'produce', '🥬', 0.95, 'seed_v1'),
  ('cheddar', 'dairy', '🧀', 0.95, 'seed_v1'),
  ('cheese block', 'dairy', '🧀', 0.95, 'seed_v1'),
  ('cheese slice', 'dairy', '🧀', 0.95, 'seed_v1'),
  ('cherry', 'produce', '🍒', 0.95, 'seed_v1'),
  ('cherry tomato', 'produce', '🍅', 0.95, 'seed_v1'),
  ('chia seed', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('chicken', 'meat', '🍗', 0.95, 'seed_v1'),
  ('chicken bouillon', 'pantry', '🍗', 0.95, 'seed_v1'),
  ('chicken breast', 'meat', '🍗', 0.95, 'seed_v1'),
  ('chicken drumstick', 'meat', '🍗', 0.95, 'seed_v1'),
  ('chicken nugget', 'meat', '🍗', 0.95, 'seed_v1'),
  ('chicken salad', 'deli', '🍗', 0.95, 'seed_v1'),
  ('chicken schnitzel', 'meat', '🍗', 0.95, 'seed_v1'),
  ('chicken tender', 'meat', '🍗', 0.95, 'seed_v1'),
  ('chicken thigh', 'meat', '🍗', 0.95, 'seed_v1'),
  ('chicken wing', 'meat', '🍗', 0.95, 'seed_v1'),
  ('chickpea', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('chicory', 'produce', '🥬', 0.95, 'seed_v1'),
  ('chili crisp', 'condiment', '🌶️', 0.95, 'seed_v1'),
  ('chili garlic sauce', 'pantry', '🧄', 0.95, 'seed_v1'),
  ('chili pepper', 'produce', '🌶️', 0.95, 'seed_v1'),
  ('chili powder', 'pantry', '🌶️', 0.95, 'seed_v1'),
  ('chip', 'snack', '🍿', 0.95, 'seed_v1'),
  ('chive', 'produce', '🥬', 0.95, 'seed_v1'),
  ('chocolate', 'snack', '🍫', 0.95, 'seed_v1'),
  ('chocolate bar', 'snack', '🍿', 0.95, 'seed_v1'),
  ('chocolate chip', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('chorizo', 'meat', '🍗', 0.95, 'seed_v1'),
  ('chutney', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('ciabatta', 'bakery', '🍞', 0.95, 'seed_v1'),
  ('cider', 'alcohol', '🍷', 0.95, 'seed_v1'),
  ('cilantro', 'produce', '🥬', 0.95, 'seed_v1'),
  ('cinnamon', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('clam', 'seafood', '🐟', 0.95, 'seed_v1'),
  ('clementine', 'produce', '🥬', 0.95, 'seed_v1'),
  ('cling film', 'household', '🧻', 0.95, 'seed_v1'),
  ('clove', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('cocoa powder', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('coconut', 'produce', '🥥', 0.95, 'seed_v1'),
  ('coconut aminos', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('coconut cream', 'international', '🥛', 0.95, 'seed_v1'),
  ('coconut flake', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('coconut milk beverage', 'dairy', '🥛', 0.95, 'seed_v1'),
  ('coconut oil', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('coconut sugar', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('coconut water', 'beverage', '💧', 0.95, 'seed_v1'),
  ('cod', 'seafood', '🐟', 0.95, 'seed_v1'),
  ('coffee', 'beverage', '☕', 0.95, 'seed_v1'),
  ('coffee bean', 'pantry', '☕', 0.95, 'seed_v1'),
  ('cola', 'beverage', '🥤', 0.95, 'seed_v1'),
  ('colby', 'dairy', '🧀', 0.95, 'seed_v1'),
  ('cold brew', 'beverage', '🥤', 0.95, 'seed_v1'),
  ('coleslaw', 'deli', '🥪', 0.95, 'seed_v1'),
  ('coleslaw kit', 'produce', '🥬', 0.95, 'seed_v1'),
  ('collard green', 'produce', '🥬', 0.95, 'seed_v1'),
  ('condensed milk', 'dairy', '🥛', 0.95, 'seed_v1'),
  ('conditioner', 'personal_care', '🧴', 0.95, 'seed_v1'),
  ('contact solution', 'personal_care', '🧴', 0.95, 'seed_v1'),
  ('cookie', 'bakery', '🍪', 0.95, 'seed_v1'),
  ('cookie mix', 'baking', '🧁', 0.95, 'seed_v1'),
  ('cooking sake', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('coriander leaf', 'produce', '🥬', 0.95, 'seed_v1'),
  ('coriander spice', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('corn', 'produce', '🌽', 0.95, 'seed_v1'),
  ('corn chip', 'snack', '🍿', 0.95, 'seed_v1'),
  ('corned beef', 'meat', '🥩', 0.95, 'seed_v1'),
  ('cornflake', 'grain', '🌾', 0.95, 'seed_v1'),
  ('cornmeal', 'grain', '🌾', 0.95, 'seed_v1'),
  ('cornstarch', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('cottage cheese', 'dairy', '🧀', 0.95, 'seed_v1'),
  ('cotton pad', 'personal_care', '🧴', 0.95, 'seed_v1'),
  ('cotton swab', 'personal_care', '🧴', 0.95, 'seed_v1'),
  ('couscous', 'grain', '🌾', 0.95, 'seed_v1'),
  ('crab', 'seafood', '🦀', 0.95, 'seed_v1'),
  ('cracker', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('cranberry', 'produce', '🫐', 0.95, 'seed_v1'),
  ('cranberry juice', 'beverage', '🧃', 0.95, 'seed_v1'),
  ('cream', 'dairy', '🥛', 0.95, 'seed_v1'),
  ('cream cheese', 'dairy', '🥛', 0.95, 'seed_v1'),
  ('cremini mushroom', 'produce', '🥬', 0.95, 'seed_v1'),
  ('croissant', 'bakery', '🥐', 0.95, 'seed_v1'),
  ('crouton', 'bakery', '🍞', 0.95, 'seed_v1'),
  ('crumpet', 'bakery', '🍞', 0.95, 'seed_v1'),
  ('crushed red pepper', 'pantry', '🫑', 0.95, 'seed_v1'),
  ('cucumber', 'produce', '🥒', 0.95, 'seed_v1'),
  ('cumin', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('cup noodle', 'pantry', '🍜', 0.95, 'seed_v1'),
  ('cupcake', 'bakery', '🍞', 0.95, 'seed_v1'),
  ('curry paste', 'international', '🍱', 0.95, 'seed_v1'),
  ('curry powder', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('custard', 'dairy', '🧀', 0.95, 'seed_v1'),
  ('daikon', 'produce', '🥬', 0.95, 'seed_v1'),
  ('dark chocolate', 'snack', '🍿', 0.95, 'seed_v1'),
  ('date', 'produce', '🥬', 0.95, 'seed_v1'),
  ('date syrup', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('deli cheese', 'deli', '🥪', 0.95, 'seed_v1'),
  ('deli ham', 'meat', '🍗', 0.95, 'seed_v1'),
  ('deli turkey', 'meat', '🦃', 0.95, 'seed_v1'),
  ('deodorant', 'personal_care', '🧴', 0.95, 'seed_v1'),
  ('diaper', 'baby', '🍼', 0.95, 'seed_v1'),
  ('diet soda', 'beverage', '🥤', 0.95, 'seed_v1'),
  ('dijon mustard', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('dill', 'produce', '🥬', 0.95, 'seed_v1'),
  ('dill pickle', 'produce', '🥬', 0.95, 'seed_v1'),
  ('dill weed', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('dish soap', 'household', '🧼', 0.95, 'seed_v1'),
  ('dish sponge', 'household', '🧻', 0.95, 'seed_v1'),
  ('dishwasher detergent', 'household', '🧴', 0.95, 'seed_v1'),
  ('dishwasher tablet', 'household', '🧻', 0.95, 'seed_v1'),
  ('disinfectant spray', 'household', '🧻', 0.95, 'seed_v1'),
  ('disinfectant wipe', 'household', '🧻', 0.95, 'seed_v1'),
  ('dog biscuit', 'pet', '🐾', 0.95, 'seed_v1'),
  ('dog chew', 'pet', '🐾', 0.95, 'seed_v1'),
  ('dog food', 'pet', '🐶', 0.95, 'seed_v1'),
  ('dog poop bag', 'pet', '🐾', 0.95, 'seed_v1'),
  ('dog treat', 'pet', '🐾', 0.95, 'seed_v1'),
  ('donut', 'bakery', '🍞', 0.95, 'seed_v1'),
  ('dragonfruit', 'produce', '🥬', 0.95, 'seed_v1'),
  ('dried fruit', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('dryer sheet', 'household', '🧻', 0.95, 'seed_v1'),
  ('dumpling wrapper', 'international', '🍱', 0.95, 'seed_v1'),
  ('egg', 'breakfast', '🥚', 0.95, 'seed_v1'),
  ('egg noodle', 'pasta', '🥚', 0.95, 'seed_v1'),
  ('egg salad', 'deli', '🥚', 0.95, 'seed_v1'),
  ('egg white', 'breakfast', '🥚', 0.95, 'seed_v1'),
  ('eggplant', 'produce', '🍆', 0.95, 'seed_v1'),
  ('endive', 'produce', '🥬', 0.95, 'seed_v1'),
  ('energy drink', 'beverage', '🥤', 0.95, 'seed_v1'),
  ('english cucumber', 'produce', '🥒', 0.95, 'seed_v1'),
  ('english muffin', 'bakery', '🍞', 0.95, 'seed_v1'),
  ('enoki mushroom', 'produce', '🥬', 0.95, 'seed_v1'),
  ('evaporated milk', 'dairy', '🥛', 0.95, 'seed_v1'),
  ('everything bagel seasoning', 'pantry', '🥯', 0.95, 'seed_v1'),
  ('extra virgin olive oil', 'pantry', '🫒', 0.95, 'seed_v1'),
  ('fabric softener', 'household', '🧻', 0.95, 'seed_v1'),
  ('face moisturizer', 'personal_care', '🧴', 0.95, 'seed_v1'),
  ('face sunscreen', 'personal_care', '🧴', 0.95, 'seed_v1'),
  ('face wash', 'personal_care', '🧴', 0.95, 'seed_v1'),
  ('falafel mix', 'international', '🍱', 0.95, 'seed_v1'),
  ('farfalle', 'pasta', '🍝', 0.95, 'seed_v1'),
  ('farro', 'grain', '🌾', 0.95, 'seed_v1'),
  ('fat-free butter', 'dairy', '🧀', 0.95, 'seed_v1'),
  ('fat-free cheddar', 'dairy', '🧀', 0.95, 'seed_v1'),
  ('fat-free cream cheese', 'dairy', '🥛', 0.95, 'seed_v1'),
  ('fat-free milk', 'dairy', '🥛', 0.95, 'seed_v1'),
  ('fat-free mozzarella', 'dairy', '🧀', 0.95, 'seed_v1'),
  ('fat-free yogurt', 'dairy', '🥣', 0.95, 'seed_v1'),
  ('fennel', 'produce', '🥬', 0.95, 'seed_v1'),
  ('fennel seed', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('feta', 'dairy', '🧀', 0.95, 'seed_v1'),
  ('fettuccine', 'pasta', '🍝', 0.95, 'seed_v1'),
  ('fig', 'produce', '🥬', 0.95, 'seed_v1'),
  ('fish fillet', 'seafood', '🐟', 0.95, 'seed_v1'),
  ('fish food', 'pet', '🐾', 0.95, 'seed_v1'),
  ('fish roe', 'seafood', '🐟', 0.95, 'seed_v1'),
  ('fish sauce', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('fish stick', 'seafood', '🐟', 0.95, 'seed_v1'),
  ('five spice', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('flatbread', 'bakery', '🍞', 0.95, 'seed_v1'),
  ('flaxseed', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('floor cleaner', 'household', '🧻', 0.95, 'seed_v1'),
  ('floss', 'personal_care', '🧴', 0.95, 'seed_v1'),
  ('flour', 'grain', '🌾', 0.95, 'seed_v1'),
  ('food coloring', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('formula', 'baby', '🍼', 0.95, 'seed_v1'),
  ('freezer bag', 'household', '🧻', 0.95, 'seed_v1'),
  ('fresh apple', 'produce', '🍎', 0.95, 'seed_v1'),
  ('fresh avocado', 'produce', '🥑', 0.95, 'seed_v1'),
  ('fresh banana', 'produce', '🍌', 0.95, 'seed_v1'),
  ('fresh blueberry', 'produce', '🫐', 0.95, 'seed_v1'),
  ('fresh broccoli', 'produce', '🥦', 0.95, 'seed_v1'),
  ('fresh cucumber', 'produce', '🥒', 0.95, 'seed_v1'),
  ('fresh grape', 'produce', '🍇', 0.95, 'seed_v1'),
  ('fresh herb mix', 'produce', '🥬', 0.95, 'seed_v1'),
  ('fresh lemon', 'produce', '🍋', 0.95, 'seed_v1'),
  ('fresh lettuce', 'produce', '🥬', 0.95, 'seed_v1'),
  ('fresh lime', 'produce', '🍋', 0.95, 'seed_v1'),
  ('fresh mango', 'produce', '🥬', 0.95, 'seed_v1'),
  ('fresh orange', 'produce', '🍊', 0.95, 'seed_v1'),
  ('fresh salsa', 'deli', '🥪', 0.95, 'seed_v1'),
  ('fresh spinach', 'produce', '🥬', 0.95, 'seed_v1'),
  ('fresh strawberry', 'produce', '🫐', 0.95, 'seed_v1'),
  ('fresh tomato', 'produce', '🍅', 0.95, 'seed_v1'),
  ('frosting', 'baking', '🧁', 0.95, 'seed_v1'),
  ('frozen berry', 'frozen', '🫐', 0.95, 'seed_v1'),
  ('frozen berry mix', 'frozen', '🫐', 0.95, 'seed_v1'),
  ('frozen blueberry', 'frozen', '🫐', 0.95, 'seed_v1'),
  ('frozen broccoli', 'frozen', '🥦', 0.95, 'seed_v1'),
  ('frozen chicken nugget', 'frozen', '🍗', 0.95, 'seed_v1'),
  ('frozen corn', 'frozen', '🧊', 0.95, 'seed_v1'),
  ('frozen dumpling', 'frozen', '🧊', 0.95, 'seed_v1'),
  ('frozen fish fillet', 'frozen', '🧊', 0.95, 'seed_v1'),
  ('frozen french fry', 'frozen', '🧊', 0.95, 'seed_v1'),
  ('frozen fruit', 'frozen', '🧊', 0.95, 'seed_v1'),
  ('frozen garlic', 'frozen', '🧄', 0.95, 'seed_v1'),
  ('frozen ginger', 'frozen', '🧊', 0.95, 'seed_v1'),
  ('frozen mango', 'frozen', '🧊', 0.95, 'seed_v1'),
  ('frozen meal', 'frozen', '🧊', 0.95, 'seed_v1'),
  ('frozen mixed vegetable', 'frozen', '🧊', 0.95, 'seed_v1'),
  ('frozen pea', 'frozen', '🧊', 0.95, 'seed_v1'),
  ('frozen pizza', 'frozen', '🍕', 0.95, 'seed_v1'),
  ('frozen pizza margherita', 'frozen', '🍕', 0.95, 'seed_v1'),
  ('frozen shrimp', 'frozen', '🍤', 0.95, 'seed_v1'),
  ('frozen spinach', 'frozen', '🧊', 0.95, 'seed_v1'),
  ('frozen spinach block', 'frozen', '🧊', 0.95, 'seed_v1'),
  ('frozen stir fry vegetable', 'frozen', '🧊', 0.95, 'seed_v1'),
  ('frozen strawberry', 'frozen', '🫐', 0.95, 'seed_v1'),
  ('frozen vegetable', 'frozen', '🧊', 0.95, 'seed_v1'),
  ('frozen waffle', 'frozen', '🧊', 0.95, 'seed_v1'),
  ('frozen yogurt', 'dairy', '🥣', 0.95, 'seed_v1'),
  ('fruit bar', 'snack', '🍿', 0.95, 'seed_v1'),
  ('fruit snack', 'snack', '🍿', 0.95, 'seed_v1'),
  ('fusilli', 'pasta', '🍝', 0.95, 'seed_v1'),
  ('garam masala', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('garbage bag', 'household', '🧻', 0.95, 'seed_v1'),
  ('garlic', 'produce', '🧄', 0.95, 'seed_v1'),
  ('garlic clove', 'produce', '🧄', 0.95, 'seed_v1'),
  ('garlic paste', 'produce', '🧄', 0.95, 'seed_v1'),
  ('garlic powder', 'pantry', '🧄', 0.95, 'seed_v1'),
  ('garlic salt', 'pantry', '🧄', 0.95, 'seed_v1'),
  ('gelatin', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('gelatin sheet', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('gelato', 'dairy', '🧀', 0.95, 'seed_v1'),
  ('ghee', 'dairy', '🧀', 0.95, 'seed_v1'),
  ('gift card', 'other', '🧺', 0.95, 'seed_v1'),
  ('gin', 'alcohol', '🍷', 0.95, 'seed_v1'),
  ('ginger', 'produce', '🥬', 0.95, 'seed_v1'),
  ('ginger ale', 'beverage', '🥤', 0.95, 'seed_v1'),
  ('ginger paste', 'produce', '🥬', 0.95, 'seed_v1'),
  ('ginger powder', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('ginger root', 'produce', '🥬', 0.95, 'seed_v1'),
  ('glass cleaner', 'household', '🧻', 0.95, 'seed_v1'),
  ('gluten-free bagel', 'bakery', '🥯', 0.95, 'seed_v1'),
  ('gluten-free bread', 'bakery', '🍞', 0.95, 'seed_v1'),
  ('gluten-free naan', 'bakery', '🍞', 0.95, 'seed_v1'),
  ('gluten-free pasta', 'pasta', '🍝', 0.95, 'seed_v1'),
  ('gluten-free tortilla', 'bakery', '🌮', 0.95, 'seed_v1'),
  ('gluten-free wrap', 'bakery', '🍞', 0.95, 'seed_v1'),
  ('gnocchi', 'pasta', '🍝', 0.95, 'seed_v1'),
  ('goat cheese', 'dairy', '🧀', 0.95, 'seed_v1'),
  ('gochujang', 'international', '🍱', 0.95, 'seed_v1'),
  ('golden apple', 'produce', '🍎', 0.95, 'seed_v1'),
  ('gouda', 'dairy', '🧀', 0.95, 'seed_v1'),
  ('granola', 'grain', '🌾', 0.95, 'seed_v1'),
  ('granola bar', 'snack', '🍿', 0.95, 'seed_v1'),
  ('grape', 'produce', '🍇', 0.95, 'seed_v1'),
  ('grape juice', 'beverage', '🧃', 0.95, 'seed_v1'),
  ('grape tomato', 'produce', '🍇', 0.95, 'seed_v1'),
  ('grapefruit', 'produce', '🍇', 0.95, 'seed_v1'),
  ('grapeseed oil', 'pantry', '🍇', 0.95, 'seed_v1'),
  ('grated parmesan', 'dairy', '🧀', 0.95, 'seed_v1'),
  ('gravy granule', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('greek yogurt', 'dairy', '🥣', 0.95, 'seed_v1'),
  ('green apple', 'produce', '🍎', 0.95, 'seed_v1'),
  ('green bean', 'produce', '🥬', 0.95, 'seed_v1'),
  ('green lentil', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('green onion', 'produce', '🧅', 0.95, 'seed_v1'),
  ('green tea', 'beverage', '🍵', 0.95, 'seed_v1'),
  ('green tea bag', 'pantry', '🍵', 0.95, 'seed_v1'),
  ('grits', 'grain', '🌾', 0.95, 'seed_v1'),
  ('ground beef', 'meat', '🥩', 0.95, 'seed_v1'),
  ('ground chicken', 'meat', '🍗', 0.95, 'seed_v1'),
  ('ground coffee', 'pantry', '☕', 0.95, 'seed_v1'),
  ('ground cumin', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('ground turkey', 'meat', '🦃', 0.95, 'seed_v1'),
  ('guacamole', 'deli', '🥪', 0.95, 'seed_v1'),
  ('guava', 'produce', '🥬', 0.95, 'seed_v1'),
  ('gummy candy', 'snack', '🍿', 0.95, 'seed_v1'),
  ('haddock', 'seafood', '🐟', 0.95, 'seed_v1'),
  ('hair gel', 'personal_care', '🧴', 0.95, 'seed_v1'),
  ('hair spray', 'personal_care', '🧴', 0.95, 'seed_v1'),
  ('half and half', 'dairy', '🧀', 0.95, 'seed_v1'),
  ('halibut', 'seafood', '🐟', 0.95, 'seed_v1'),
  ('halloumi', 'dairy', '🧀', 0.95, 'seed_v1'),
  ('ham', 'meat', '🍗', 0.95, 'seed_v1'),
  ('hamburger bun', 'bakery', '🍞', 0.95, 'seed_v1'),
  ('hand cream', 'personal_care', '🥛', 0.95, 'seed_v1'),
  ('hand lotion', 'personal_care', '🧴', 0.95, 'seed_v1'),
  ('hand sanitizer', 'household', '🧻', 0.95, 'seed_v1'),
  ('hand soap', 'personal_care', '🧼', 0.95, 'seed_v1'),
  ('hand wash', 'personal_care', '🧴', 0.95, 'seed_v1'),
  ('harissa', 'international', '🍱', 0.95, 'seed_v1'),
  ('hash brown', 'breakfast', '🥣', 0.95, 'seed_v1'),
  ('hazelnut', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('heavy cream', 'dairy', '🥛', 0.95, 'seed_v1'),
  ('heirloom tomato', 'produce', '🍅', 0.95, 'seed_v1'),
  ('hemp seed', 'nut_seed', '🥜', 0.95, 'seed_v1'),
  ('herbal tea', 'beverage', '🍵', 0.95, 'seed_v1'),
  ('herbal tea bag', 'pantry', '🍵', 0.95, 'seed_v1'),
  ('hoisin sauce', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('honey', 'pantry', '🍯', 0.95, 'seed_v1'),
  ('honey mustard', 'condiment', '🧂', 0.95, 'seed_v1'),
  ('honeydew', 'produce', '🥬', 0.95, 'seed_v1'),
  ('hot chocolate mix', 'beverage', '🥤', 0.95, 'seed_v1'),
  ('hot dog', 'meat', '🍗', 0.95, 'seed_v1'),
  ('hot dog bun', 'bakery', '🍞', 0.95, 'seed_v1'),
  ('hot sauce', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('hummus', 'deli', '🥪', 0.95, 'seed_v1'),
  ('ice cream', 'dairy', '🍨', 0.95, 'seed_v1'),
  ('ice cream tub', 'frozen', '🥛', 0.95, 'seed_v1'),
  ('ice cube', 'frozen', '🧊', 0.95, 'seed_v1'),
  ('iceberg lettuce', 'produce', '🥬', 0.95, 'seed_v1'),
  ('iced coffee', 'beverage', '☕', 0.95, 'seed_v1'),
  ('iced tea', 'beverage', '🍵', 0.95, 'seed_v1'),
  ('icing sugar', 'baking', '🧁', 0.95, 'seed_v1'),
  ('instant coffee', 'pantry', '☕', 0.95, 'seed_v1'),
  ('instant gravy', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('instant mash', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('instant noodle', 'pantry', '🍜', 0.95, 'seed_v1'),
  ('instant noodle seasoning', 'pantry', '🍜', 0.95, 'seed_v1'),
  ('instant oatmeal', 'grain', '🌾', 0.95, 'seed_v1'),
  ('instant oats', 'grain', '🌾', 0.95, 'seed_v1'),
  ('instant rice', 'pantry', '🍚', 0.95, 'seed_v1'),
  ('instant soup', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('instant yeast', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('italian dressing', 'condiment', '🧂', 0.95, 'seed_v1'),
  ('italian sausage', 'meat', '🌭', 0.95, 'seed_v1'),
  ('italian seasoning', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('jackfruit', 'produce', '🥬', 0.95, 'seed_v1'),
  ('jalapeno', 'produce', '🥬', 0.95, 'seed_v1'),
  ('jam', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('jasmine rice', 'grain', '🍚', 0.95, 'seed_v1'),
  ('jerk seasoning', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('jicama', 'produce', '🥬', 0.95, 'seed_v1'),
  ('juice', 'beverage', '🧃', 0.95, 'seed_v1'),
  ('kale', 'produce', '🥬', 0.95, 'seed_v1'),
  ('kefir', 'dairy', '🧀', 0.95, 'seed_v1'),
  ('ketchup', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('kidney bean', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('kimchi', 'international', '🍱', 0.95, 'seed_v1'),
  ('kitchen towel', 'household', '🧻', 0.95, 'seed_v1'),
  ('kiwi', 'produce', '🥝', 0.95, 'seed_v1'),
  ('kohlrabi', 'produce', '🥬', 0.95, 'seed_v1'),
  ('kosher salt', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('kumquat', 'produce', '🥬', 0.95, 'seed_v1'),
  ('labneh', 'international', '🍱', 0.95, 'seed_v1'),
  ('lactose-free butter', 'dairy', '🧀', 0.95, 'seed_v1'),
  ('lactose-free cheddar', 'dairy', '🧀', 0.95, 'seed_v1'),
  ('lactose-free cream cheese', 'dairy', '🥛', 0.95, 'seed_v1'),
  ('lactose-free milk', 'dairy', '🥛', 0.95, 'seed_v1'),
  ('lactose-free mozzarella', 'dairy', '🧀', 0.95, 'seed_v1'),
  ('lactose-free yogurt', 'dairy', '🥣', 0.95, 'seed_v1'),
  ('lager', 'alcohol', '🍷', 0.95, 'seed_v1'),
  ('lamb', 'meat', '🍗', 0.95, 'seed_v1'),
  ('lamb chop', 'meat', '🍗', 0.95, 'seed_v1'),
  ('lamb leg', 'meat', '🍗', 0.95, 'seed_v1'),
  ('lasagna sheet', 'pasta', '🍝', 0.95, 'seed_v1'),
  ('laundry detergent', 'household', '🧴', 0.95, 'seed_v1'),
  ('leek', 'produce', '🥬', 0.95, 'seed_v1'),
  ('lemon', 'produce', '🍋', 0.95, 'seed_v1'),
  ('lemon pepper seasoning', 'pantry', '🍋', 0.95, 'seed_v1'),
  ('lemonade', 'beverage', '🍋', 0.95, 'seed_v1'),
  ('lemongrass', 'produce', '🍋', 0.95, 'seed_v1'),
  ('lentil', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('lettuce', 'produce', '🥬', 0.95, 'seed_v1'),
  ('lettuce heart', 'produce', '🥬', 0.95, 'seed_v1'),
  ('light bulb', 'household', '🧻', 0.95, 'seed_v1'),
  ('lime', 'produce', '🍋', 0.95, 'seed_v1'),
  ('linguine', 'pasta', '🍝', 0.95, 'seed_v1'),
  ('lip balm', 'personal_care', '🧴', 0.95, 'seed_v1'),
  ('liqueur', 'alcohol', '🍷', 0.95, 'seed_v1'),
  ('liquid smoke', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('lobster', 'seafood', '🦞', 0.95, 'seed_v1'),
  ('lotion', 'personal_care', '🧴', 0.95, 'seed_v1'),
  ('low-fat butter', 'dairy', '🧀', 0.95, 'seed_v1'),
  ('low-fat cheddar', 'dairy', '🧀', 0.95, 'seed_v1'),
  ('low-fat cream cheese', 'dairy', '🥛', 0.95, 'seed_v1'),
  ('low-fat milk', 'dairy', '🥛', 0.95, 'seed_v1'),
  ('low-fat mozzarella', 'dairy', '🧀', 0.95, 'seed_v1'),
  ('low-fat yogurt', 'dairy', '🥣', 0.95, 'seed_v1'),
  ('lychee', 'produce', '🥬', 0.95, 'seed_v1'),
  ('macadamia', 'nut_seed', '🥜', 0.95, 'seed_v1'),
  ('macaroni', 'pasta', '🍝', 0.95, 'seed_v1'),
  ('mackerel', 'seafood', '🐟', 0.95, 'seed_v1'),
  ('makeup remover', 'personal_care', '🧴', 0.95, 'seed_v1'),
  ('malt vinegar', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('mandarin', 'produce', '🥬', 0.95, 'seed_v1'),
  ('mango', 'produce', '🥭', 0.95, 'seed_v1'),
  ('manicotti', 'pasta', '🍝', 0.95, 'seed_v1'),
  ('maple syrup', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('marshmallow', 'snack', '🍿', 0.95, 'seed_v1'),
  ('mascarpone', 'dairy', '🧀', 0.95, 'seed_v1'),
  ('match', 'household', '🧻', 0.95, 'seed_v1'),
  ('mayonnaise', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('meatball', 'meat', '🍗', 0.95, 'seed_v1'),
  ('melon', 'produce', '🥬', 0.95, 'seed_v1'),
  ('microwave rice', 'grain', '🍚', 0.95, 'seed_v1'),
  ('milk', 'dairy', '🥛', 0.95, 'seed_v1'),
  ('milk chocolate', 'snack', '🥛', 0.95, 'seed_v1'),
  ('milk powder', 'dairy', '🥛', 0.95, 'seed_v1'),
  ('milkshake', 'beverage', '🥛', 0.95, 'seed_v1'),
  ('mineral water', 'beverage', '💧', 0.95, 'seed_v1'),
  ('mint', 'produce', '🥬', 0.95, 'seed_v1'),
  ('mirin', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('miso', 'international', '🍱', 0.95, 'seed_v1'),
  ('mixed greens', 'produce', '🥬', 0.95, 'seed_v1'),
  ('molasses', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('monterey jack', 'dairy', '🧀', 0.95, 'seed_v1'),
  ('mouthwash', 'personal_care', '🧴', 0.95, 'seed_v1'),
  ('mozzarella', 'dairy', '🧀', 0.95, 'seed_v1'),
  ('msg', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('muesli', 'grain', '🌾', 0.95, 'seed_v1'),
  ('muffin', 'bakery', '🍞', 0.95, 'seed_v1'),
  ('muffin liner', 'baking', '🧁', 0.95, 'seed_v1'),
  ('multigrain bread', 'bakery', '🍞', 0.95, 'seed_v1'),
  ('mushroom', 'produce', '🍄', 0.95, 'seed_v1'),
  ('mussel', 'seafood', '🐟', 0.95, 'seed_v1'),
  ('mustard', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('mustard powder', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('mustard seed', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('naan', 'bakery', '🍞', 0.95, 'seed_v1'),
  ('naan bread', 'international', '🍞', 0.95, 'seed_v1'),
  ('napa cabbage', 'produce', '🥬', 0.95, 'seed_v1'),
  ('napkin', 'household', '🧻', 0.95, 'seed_v1'),
  ('navy bean', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('nectarine', 'produce', '🥬', 0.95, 'seed_v1'),
  ('nori', 'international', '🍱', 0.95, 'seed_v1'),
  ('nut butter', 'nut_seed', '🥜', 0.95, 'seed_v1'),
  ('nut mix', 'snack', '🍿', 0.95, 'seed_v1'),
  ('nutella', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('nutmeg', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('oat', 'grain', '🌾', 0.95, 'seed_v1'),
  ('oat bran', 'grain', '🌾', 0.95, 'seed_v1'),
  ('oat milk', 'dairy', '🥛', 0.95, 'seed_v1'),
  ('oatmeal', 'grain', '🌾', 0.95, 'seed_v1'),
  ('oatmeal packet', 'breakfast', '🥣', 0.95, 'seed_v1'),
  ('octopus', 'seafood', '🐟', 0.95, 'seed_v1'),
  ('okra', 'produce', '🥬', 0.95, 'seed_v1'),
  ('olive oil', 'pantry', '🫒', 0.95, 'seed_v1'),
  ('olive tapenade', 'deli', '🫒', 0.95, 'seed_v1'),
  ('onion', 'produce', '🧅', 0.95, 'seed_v1'),
  ('onion powder', 'pantry', '🧅', 0.95, 'seed_v1'),
  ('onion salt', 'pantry', '🧅', 0.95, 'seed_v1'),
  ('orange', 'produce', '🍊', 0.95, 'seed_v1'),
  ('orange juice', 'beverage', '🧃', 0.95, 'seed_v1'),
  ('orange marmalade', 'pantry', '🍊', 0.95, 'seed_v1'),
  ('oregano', 'produce', '🥬', 0.95, 'seed_v1'),
  ('organic apple', 'produce', '🍎', 0.95, 'seed_v1'),
  ('organic avocado', 'produce', '🥑', 0.95, 'seed_v1'),
  ('organic banana', 'produce', '🍌', 0.95, 'seed_v1'),
  ('organic blueberry', 'produce', '🫐', 0.95, 'seed_v1'),
  ('organic broccoli', 'produce', '🥦', 0.95, 'seed_v1'),
  ('organic cucumber', 'produce', '🥒', 0.95, 'seed_v1'),
  ('organic grape', 'produce', '🍇', 0.95, 'seed_v1'),
  ('organic lemon', 'produce', '🍋', 0.95, 'seed_v1'),
  ('organic lettuce', 'produce', '🥬', 0.95, 'seed_v1'),
  ('organic lime', 'produce', '🍋', 0.95, 'seed_v1'),
  ('organic mango', 'produce', '🥬', 0.95, 'seed_v1'),
  ('organic orange', 'produce', '🍊', 0.95, 'seed_v1'),
  ('organic spinach', 'produce', '🥬', 0.95, 'seed_v1'),
  ('organic strawberry', 'produce', '🫐', 0.95, 'seed_v1'),
  ('organic tomato', 'produce', '🍅', 0.95, 'seed_v1'),
  ('orzo', 'pasta', '🍝', 0.95, 'seed_v1'),
  ('oyster', 'seafood', '🦪', 0.95, 'seed_v1'),
  ('oyster mushroom', 'produce', '🦪', 0.95, 'seed_v1'),
  ('oyster sauce', 'pantry', '🦪', 0.95, 'seed_v1'),
  ('pacifier', 'baby', '🍼', 0.95, 'seed_v1'),
  ('pancake', 'bakery', '🥞', 0.95, 'seed_v1'),
  ('pancake mix', 'breakfast', '🥣', 0.95, 'seed_v1'),
  ('panko', 'grain', '🌾', 0.95, 'seed_v1'),
  ('papaya', 'produce', '🥬', 0.95, 'seed_v1'),
  ('paper cup', 'household', '🧻', 0.95, 'seed_v1'),
  ('paper plate', 'household', '🧻', 0.95, 'seed_v1'),
  ('paper towel', 'household', '🧻', 0.95, 'seed_v1'),
  ('paprika', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('parchment paper', 'baking', '🧁', 0.95, 'seed_v1'),
  ('parmesan', 'dairy', '🧀', 0.95, 'seed_v1'),
  ('parsley', 'produce', '🥬', 0.95, 'seed_v1'),
  ('parsnip', 'produce', '🥬', 0.95, 'seed_v1'),
  ('passionfruit', 'produce', '🥬', 0.95, 'seed_v1'),
  ('pasta', 'pasta', '🍝', 0.95, 'seed_v1'),
  ('pasta bake sauce', 'pantry', '🍝', 0.95, 'seed_v1'),
  ('pasta salad', 'deli', '🍝', 0.95, 'seed_v1'),
  ('pasta sauce', 'pantry', '🍝', 0.95, 'seed_v1'),
  ('pastrami', 'meat', '🍗', 0.95, 'seed_v1'),
  ('pea', 'produce', '🥬', 0.95, 'seed_v1'),
  ('peach', 'produce', '🍑', 0.95, 'seed_v1'),
  ('peanut', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('peanut butter', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('pear', 'produce', '🍐', 0.95, 'seed_v1'),
  ('pecan', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('penne', 'pasta', '🍝', 0.95, 'seed_v1'),
  ('pepper', 'produce', '🫑', 0.95, 'seed_v1'),
  ('pepper jack', 'dairy', '🫑', 0.95, 'seed_v1'),
  ('pepperoni', 'meat', '🫑', 0.95, 'seed_v1'),
  ('persimmon', 'produce', '🥬', 0.95, 'seed_v1'),
  ('pesto', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('pet shampoo', 'pet', '🧴', 0.95, 'seed_v1'),
  ('pet waste bag', 'pet', '🐾', 0.95, 'seed_v1'),
  ('pho noodle', 'international', '🍜', 0.95, 'seed_v1'),
  ('pickle', 'produce', '🥬', 0.95, 'seed_v1'),
  ('pickle chip', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('pickle relish', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('pickle spear', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('pickled cucumber', 'pantry', '🥒', 0.95, 'seed_v1'),
  ('pickled jalapeno', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('pickled onion', 'pantry', '🧅', 0.95, 'seed_v1'),
  ('pie crust', 'bakery', '🍞', 0.95, 'seed_v1'),
  ('pie filling', 'baking', '🧁', 0.95, 'seed_v1'),
  ('pine nut', 'nut_seed', '🥜', 0.95, 'seed_v1'),
  ('pineapple', 'produce', '🍍', 0.95, 'seed_v1'),
  ('pinto bean', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('pistachio', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('pita', 'bakery', '🍞', 0.95, 'seed_v1'),
  ('pita bread', 'international', '🍞', 0.95, 'seed_v1'),
  ('pita chip', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('pita pocket', 'bakery', '🍞', 0.95, 'seed_v1'),
  ('pizza dough', 'bakery', '🍕', 0.95, 'seed_v1'),
  ('plain yogurt', 'dairy', '🥣', 0.95, 'seed_v1'),
  ('plantain', 'produce', '🥬', 0.95, 'seed_v1'),
  ('plastic cutlery', 'household', '🧻', 0.95, 'seed_v1'),
  ('plastic wrap', 'household', '🧻', 0.95, 'seed_v1'),
  ('plum', 'produce', '🥬', 0.95, 'seed_v1'),
  ('poblano pepper', 'produce', '🫑', 0.95, 'seed_v1'),
  ('polenta', 'grain', '🌾', 0.95, 'seed_v1'),
  ('pomegranate', 'produce', '🥬', 0.95, 'seed_v1'),
  ('popcorn', 'snack', '🍿', 0.95, 'seed_v1'),
  ('popcorn kernel', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('popcorn microwave', 'snack', '🍿', 0.95, 'seed_v1'),
  ('popsicle', 'snack', '🍿', 0.95, 'seed_v1'),
  ('pork', 'meat', '🥓', 0.95, 'seed_v1'),
  ('pork belly', 'meat', '🥓', 0.95, 'seed_v1'),
  ('pork chop', 'meat', '🥓', 0.95, 'seed_v1'),
  ('pork loin', 'meat', '🥓', 0.95, 'seed_v1'),
  ('pork mince', 'meat', '🥓', 0.95, 'seed_v1'),
  ('portobello mushroom', 'produce', '🥬', 0.95, 'seed_v1'),
  ('potato', 'produce', '🥔', 0.95, 'seed_v1'),
  ('potato chip', 'snack', '🥔', 0.95, 'seed_v1'),
  ('potato salad', 'deli', '🥔', 0.95, 'seed_v1'),
  ('powdered gelatin', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('powdered sugar', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('prawn', 'seafood', '🐟', 0.95, 'seed_v1'),
  ('pretzel', 'pantry', '🥨', 0.95, 'seed_v1'),
  ('pretzel stick', 'snack', '🥨', 0.95, 'seed_v1'),
  ('prosciutto', 'meat', '🍗', 0.95, 'seed_v1'),
  ('protein bar', 'snack', '🍿', 0.95, 'seed_v1'),
  ('protein cookie', 'snack', '🍿', 0.95, 'seed_v1'),
  ('protein yogurt', 'dairy', '🥣', 0.95, 'seed_v1'),
  ('provolone', 'dairy', '🧀', 0.95, 'seed_v1'),
  ('prune', 'produce', '🥬', 0.95, 'seed_v1'),
  ('pudding', 'dairy', '🧀', 0.95, 'seed_v1'),
  ('pumpkin', 'produce', '🥬', 0.95, 'seed_v1'),
  ('pumpkin seed', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('quince', 'produce', '🥬', 0.95, 'seed_v1'),
  ('quinoa', 'grain', '🌾', 0.95, 'seed_v1'),
  ('radicchio', 'produce', '🥬', 0.95, 'seed_v1'),
  ('radish', 'produce', '🥬', 0.95, 'seed_v1'),
  ('raisin', 'produce', '🥬', 0.95, 'seed_v1'),
  ('ramen', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('ramen broth', 'international', '🍱', 0.95, 'seed_v1'),
  ('ramen noodle', 'pasta', '🍜', 0.95, 'seed_v1'),
  ('ramen packet', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('ranch dressing', 'condiment', '🧂', 0.95, 'seed_v1'),
  ('raspberry', 'produce', '🫐', 0.95, 'seed_v1'),
  ('raspberry jam', 'pantry', '🫐', 0.95, 'seed_v1'),
  ('ravioli', 'pasta', '🍝', 0.95, 'seed_v1'),
  ('razor', 'personal_care', '🧴', 0.95, 'seed_v1'),
  ('recycling bag', 'household', '🧻', 0.95, 'seed_v1'),
  ('red apple', 'produce', '🍎', 0.95, 'seed_v1'),
  ('red cabbage', 'produce', '🥬', 0.95, 'seed_v1'),
  ('red lentil', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('red onion', 'produce', '🧅', 0.95, 'seed_v1'),
  ('red potato', 'produce', '🥔', 0.95, 'seed_v1'),
  ('red wine', 'alcohol', '🍷', 0.95, 'seed_v1'),
  ('red wine vinegar', 'pantry', '🍷', 0.95, 'seed_v1'),
  ('relish', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('reusable bag', 'other', '🧺', 0.95, 'seed_v1'),
  ('ribeye', 'meat', '🍗', 0.95, 'seed_v1'),
  ('rice', 'grain', '🍚', 0.95, 'seed_v1'),
  ('rice cake', 'pantry', '🍚', 0.95, 'seed_v1'),
  ('rice cake caramel', 'snack', '🍚', 0.95, 'seed_v1'),
  ('rice cracker', 'snack', '🍚', 0.95, 'seed_v1'),
  ('rice noodle', 'pasta', '🍚', 0.95, 'seed_v1'),
  ('rice noodle thin', 'pasta', '🍚', 0.95, 'seed_v1'),
  ('rice noodle wide', 'pasta', '🍚', 0.95, 'seed_v1'),
  ('rice paper', 'international', '🍚', 0.95, 'seed_v1'),
  ('rice vinegar', 'pantry', '🍚', 0.95, 'seed_v1'),
  ('rice vinegar seasoning', 'pantry', '🍚', 0.95, 'seed_v1'),
  ('ricotta', 'dairy', '🧀', 0.95, 'seed_v1'),
  ('rigatoni', 'pasta', '🍝', 0.95, 'seed_v1'),
  ('ripe apple', 'produce', '🍎', 0.95, 'seed_v1'),
  ('ripe avocado', 'produce', '🥑', 0.95, 'seed_v1'),
  ('ripe banana', 'produce', '🍌', 0.95, 'seed_v1'),
  ('ripe blueberry', 'produce', '🫐', 0.95, 'seed_v1'),
  ('ripe broccoli', 'produce', '🥦', 0.95, 'seed_v1'),
  ('ripe cucumber', 'produce', '🥒', 0.95, 'seed_v1'),
  ('ripe grape', 'produce', '🍇', 0.95, 'seed_v1'),
  ('ripe lemon', 'produce', '🍋', 0.95, 'seed_v1'),
  ('ripe lettuce', 'produce', '🥬', 0.95, 'seed_v1'),
  ('ripe lime', 'produce', '🍋', 0.95, 'seed_v1'),
  ('ripe mango', 'produce', '🥬', 0.95, 'seed_v1'),
  ('ripe orange', 'produce', '🍊', 0.95, 'seed_v1'),
  ('ripe spinach', 'produce', '🥬', 0.95, 'seed_v1'),
  ('ripe strawberry', 'produce', '🫐', 0.95, 'seed_v1'),
  ('ripe tomato', 'produce', '🍅', 0.95, 'seed_v1'),
  ('roll', 'bakery', '🍞', 0.95, 'seed_v1'),
  ('rolled oat', 'grain', '🌾', 0.95, 'seed_v1'),
  ('roma tomato', 'produce', '🍅', 0.95, 'seed_v1'),
  ('romaine', 'produce', '🥬', 0.95, 'seed_v1'),
  ('rosemary', 'produce', '🥬', 0.95, 'seed_v1'),
  ('rubber glove', 'household', '🧻', 0.95, 'seed_v1'),
  ('rum', 'alcohol', '🍷', 0.95, 'seed_v1'),
  ('russet potato', 'produce', '🥔', 0.95, 'seed_v1'),
  ('rutabaga', 'produce', '🥬', 0.95, 'seed_v1'),
  ('rye bread', 'bakery', '🍞', 0.95, 'seed_v1'),
  ('saffron', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('sage', 'produce', '🥬', 0.95, 'seed_v1'),
  ('salad kit', 'produce', '🥬', 0.95, 'seed_v1'),
  ('salami', 'meat', '🍗', 0.95, 'seed_v1'),
  ('salmon', 'seafood', '🐟', 0.95, 'seed_v1'),
  ('salsa', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('salsa fresca', 'deli', '🥪', 0.95, 'seed_v1'),
  ('salt', 'pantry', '🧂', 0.95, 'seed_v1'),
  ('salted butter', 'dairy', '🧀', 0.95, 'seed_v1'),
  ('sambal oelek', 'international', '🍱', 0.95, 'seed_v1'),
  ('sandwich bag', 'household', '🧻', 0.95, 'seed_v1'),
  ('sanitary pad', 'personal_care', '🧴', 0.95, 'seed_v1'),
  ('sardine', 'seafood', '🐟', 0.95, 'seed_v1'),
  ('sausage', 'meat', '🌭', 0.95, 'seed_v1'),
  ('scallion', 'produce', '🥬', 0.95, 'seed_v1'),
  ('scallop', 'seafood', '🐟', 0.95, 'seed_v1'),
  ('scone', 'bakery', '🍞', 0.95, 'seed_v1'),
  ('scrub brush', 'household', '🧻', 0.95, 'seed_v1'),
  ('sea salt', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('seaweed snack', 'snack', '🍿', 0.95, 'seed_v1'),
  ('seed butter', 'nut_seed', '🥜', 0.95, 'seed_v1'),
  ('self-raising flour', 'grain', '🌾', 0.95, 'seed_v1'),
  ('semi-skim milk', 'dairy', '🥛', 0.95, 'seed_v1'),
  ('semolina', 'grain', '🌾', 0.95, 'seed_v1'),
  ('serrano pepper', 'produce', '🫑', 0.95, 'seed_v1'),
  ('sesame oil', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('sesame seed', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('shallot', 'produce', '🥬', 0.95, 'seed_v1'),
  ('shampoo', 'personal_care', '🧴', 0.95, 'seed_v1'),
  ('shaving cream', 'personal_care', '🥛', 0.95, 'seed_v1'),
  ('shawarma sauce', 'international', '🍱', 0.95, 'seed_v1'),
  ('shawarma seasoning', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('shiitake mushroom', 'produce', '🥬', 0.95, 'seed_v1'),
  ('shopping bag', 'other', '🧺', 0.95, 'seed_v1'),
  ('short rib', 'meat', '🍗', 0.95, 'seed_v1'),
  ('shredded cheese', 'dairy', '🧀', 0.95, 'seed_v1'),
  ('shredded coconut', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('shrimp', 'seafood', '🍤', 0.95, 'seed_v1'),
  ('sirloin', 'meat', '🍗', 0.95, 'seed_v1'),
  ('skim milk', 'dairy', '🥛', 0.95, 'seed_v1'),
  ('smoked ham', 'meat', '🍗', 0.95, 'seed_v1'),
  ('smoked paprika', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('smoked salmon', 'seafood', '🐟', 0.95, 'seed_v1'),
  ('smoked trout', 'seafood', '🐟', 0.95, 'seed_v1'),
  ('snap pea', 'produce', '🥬', 0.95, 'seed_v1'),
  ('snapper', 'seafood', '🐟', 0.95, 'seed_v1'),
  ('snow pea', 'produce', '🥬', 0.95, 'seed_v1'),
  ('soap', 'personal_care', '🧼', 0.95, 'seed_v1'),
  ('soba noodle', 'pasta', '🍜', 0.95, 'seed_v1'),
  ('soda', 'beverage', '🥤', 0.95, 'seed_v1'),
  ('sorbet', 'dairy', '🧀', 0.95, 'seed_v1'),
  ('sour cream', 'dairy', '🥛', 0.95, 'seed_v1'),
  ('sourdough', 'bakery', '🍞', 0.95, 'seed_v1'),
  ('soy milk', 'dairy', '🥛', 0.95, 'seed_v1'),
  ('soy sauce', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('spaghetti', 'pasta', '🍝', 0.95, 'seed_v1'),
  ('spaghetti squash', 'produce', '🍝', 0.95, 'seed_v1'),
  ('sparkling lemonade', 'beverage', '🍋', 0.95, 'seed_v1'),
  ('sparkling water', 'beverage', '💧', 0.95, 'seed_v1'),
  ('sparkling wine', 'alcohol', '🍷', 0.95, 'seed_v1'),
  ('spinach', 'produce', '🥬', 0.95, 'seed_v1'),
  ('spinach dip', 'deli', '🥪', 0.95, 'seed_v1'),
  ('split pea', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('sponge', 'household', '🧻', 0.95, 'seed_v1'),
  ('sports drink', 'beverage', '🥤', 0.95, 'seed_v1'),
  ('spring onion', 'produce', '🧅', 0.95, 'seed_v1'),
  ('sprinkle', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('sriracha', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('stain remover', 'household', '🧻', 0.95, 'seed_v1'),
  ('starfruit', 'produce', '🥬', 0.95, 'seed_v1'),
  ('steak', 'meat', '🥩', 0.95, 'seed_v1'),
  ('steel cut oat', 'grain', '🌾', 0.95, 'seed_v1'),
  ('stir fry kit', 'produce', '🥬', 0.95, 'seed_v1'),
  ('stir fry sauce', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('stock cube', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('storage container', 'household', '🧻', 0.95, 'seed_v1'),
  ('stout', 'alcohol', '🍷', 0.95, 'seed_v1'),
  ('strawberry', 'produce', '🍓', 0.95, 'seed_v1'),
  ('strawberry jam', 'pantry', '🫐', 0.95, 'seed_v1'),
  ('strawberry yogurt', 'dairy', '🥣', 0.95, 'seed_v1'),
  ('string cheese', 'dairy', '🧀', 0.95, 'seed_v1'),
  ('sugar', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('sumac', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('summer squash', 'produce', '🥬', 0.95, 'seed_v1'),
  ('sun-dried tomato', 'produce', '🍅', 0.95, 'seed_v1'),
  ('sunflower butter', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('sunflower oil', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('sunflower seed', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('sunscreen', 'personal_care', '🧴', 0.95, 'seed_v1'),
  ('surface wipe', 'household', '🧻', 0.95, 'seed_v1'),
  ('sushi ginger', 'international', '🍱', 0.95, 'seed_v1'),
  ('sushi rice', 'grain', '🍚', 0.95, 'seed_v1'),
  ('sweet chili sauce', 'pantry', '🌶️', 0.95, 'seed_v1'),
  ('sweet potato', 'produce', '🍠', 0.95, 'seed_v1'),
  ('swiss cheese', 'dairy', '🧀', 0.95, 'seed_v1'),
  ('t-bone', 'meat', '🍗', 0.95, 'seed_v1'),
  ('tabbouleh', 'international', '🍱', 0.95, 'seed_v1'),
  ('taco seasoning', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('taco shell', 'bakery', '🍞', 0.95, 'seed_v1'),
  ('tagliatelle', 'pasta', '🍝', 0.95, 'seed_v1'),
  ('tahini', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('tamari', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('tamarind paste', 'international', '🍱', 0.95, 'seed_v1'),
  ('tampon', 'personal_care', '🧴', 0.95, 'seed_v1'),
  ('tangerine', 'produce', '🥬', 0.95, 'seed_v1'),
  ('tarragon', 'produce', '🥬', 0.95, 'seed_v1'),
  ('tea', 'beverage', '🍵', 0.95, 'seed_v1'),
  ('tea bag', 'pantry', '🍵', 0.95, 'seed_v1'),
  ('teething snack', 'baby', '🍼', 0.95, 'seed_v1'),
  ('tempeh', 'international', '🍱', 0.95, 'seed_v1'),
  ('tequila', 'alcohol', '🍷', 0.95, 'seed_v1'),
  ('teriyaki sauce', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('thyme', 'produce', '🥬', 0.95, 'seed_v1'),
  ('tilapia', 'seafood', '🐟', 0.95, 'seed_v1'),
  ('tissue', 'household', '🧻', 0.95, 'seed_v1'),
  ('tofu', 'international', '🍱', 0.95, 'seed_v1'),
  ('toilet brush', 'household', '🧻', 0.95, 'seed_v1'),
  ('toilet cleaner', 'household', '🧻', 0.95, 'seed_v1'),
  ('toilet paper', 'household', '🧻', 0.95, 'seed_v1'),
  ('tomatillo', 'produce', '🥬', 0.95, 'seed_v1'),
  ('tomato', 'produce', '🍅', 0.95, 'seed_v1'),
  ('tomato passata', 'pantry', '🍅', 0.95, 'seed_v1'),
  ('tomato paste', 'pantry', '🍅', 0.95, 'seed_v1'),
  ('tomato sauce', 'pantry', '🍅', 0.95, 'seed_v1'),
  ('tonic water', 'beverage', '💧', 0.95, 'seed_v1'),
  ('toothbrush', 'personal_care', '🪥', 0.95, 'seed_v1'),
  ('toothpaste', 'personal_care', '🪥', 0.95, 'seed_v1'),
  ('tortellini', 'pasta', '🍝', 0.95, 'seed_v1'),
  ('tortilla', 'bakery', '🌮', 0.95, 'seed_v1'),
  ('tortilla chip', 'pantry', '🌮', 0.95, 'seed_v1'),
  ('tortilla wrap', 'international', '🌮', 0.95, 'seed_v1'),
  ('trail mix', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('trash bag', 'household', '🗑️', 0.95, 'seed_v1'),
  ('trout', 'seafood', '🐟', 0.95, 'seed_v1'),
  ('tuna', 'seafood', '🐟', 0.95, 'seed_v1'),
  ('tuna steak', 'seafood', '🥩', 0.95, 'seed_v1'),
  ('turkey', 'meat', '🦃', 0.95, 'seed_v1'),
  ('turkey breast', 'meat', '🦃', 0.95, 'seed_v1'),
  ('turkey mince', 'meat', '🦃', 0.95, 'seed_v1'),
  ('turmeric', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('turnip', 'produce', '🥬', 0.95, 'seed_v1'),
  ('tzatziki', 'deli', '🥪', 0.95, 'seed_v1'),
  ('udon noodle', 'pasta', '🍜', 0.95, 'seed_v1'),
  ('udon soup base', 'international', '🍱', 0.95, 'seed_v1'),
  ('unsalted butter', 'dairy', '🧀', 0.95, 'seed_v1'),
  ('vanilla extract', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('vanilla yogurt', 'dairy', '🥣', 0.95, 'seed_v1'),
  ('veal', 'meat', '🍗', 0.95, 'seed_v1'),
  ('vegetable bouillon', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('vegetable oil', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('vegetable soup mix', 'produce', '🥬', 0.95, 'seed_v1'),
  ('vermicelli', 'pasta', '🍝', 0.95, 'seed_v1'),
  ('vinaigrette', 'condiment', '🧂', 0.95, 'seed_v1'),
  ('vodka', 'alcohol', '🍸', 0.95, 'seed_v1'),
  ('waffle', 'bakery', '🧇', 0.95, 'seed_v1'),
  ('waffle mix', 'breakfast', '🥣', 0.95, 'seed_v1'),
  ('walnut', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('wasabi', 'condiment', '🧂', 0.95, 'seed_v1'),
  ('water', 'beverage', '💧', 0.95, 'seed_v1'),
  ('watercress', 'produce', '💧', 0.95, 'seed_v1'),
  ('watermelon', 'produce', '🍉', 0.95, 'seed_v1'),
  ('wax bean', 'produce', '🥬', 0.95, 'seed_v1'),
  ('whipped cream', 'dairy', '🥛', 0.95, 'seed_v1'),
  ('whipping cream', 'dairy', '🥛', 0.95, 'seed_v1'),
  ('whiskey', 'alcohol', '🥃', 0.95, 'seed_v1'),
  ('white bread', 'bakery', '🍞', 0.95, 'seed_v1'),
  ('white chocolate chip', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('white onion', 'produce', '🧅', 0.95, 'seed_v1'),
  ('white pepper', 'pantry', '🫑', 0.95, 'seed_v1'),
  ('white rice', 'grain', '🍚', 0.95, 'seed_v1'),
  ('white vinegar', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('white wine', 'alcohol', '🍷', 0.95, 'seed_v1'),
  ('whole chicken', 'meat', '🍗', 0.95, 'seed_v1'),
  ('whole milk', 'dairy', '🥛', 0.95, 'seed_v1'),
  ('whole wheat bagel', 'bakery', '🥯', 0.95, 'seed_v1'),
  ('whole wheat bread', 'bakery', '🍞', 0.95, 'seed_v1'),
  ('whole wheat flour', 'grain', '🌾', 0.95, 'seed_v1'),
  ('whole wheat naan', 'bakery', '🍞', 0.95, 'seed_v1'),
  ('whole wheat pasta', 'pasta', '🍝', 0.95, 'seed_v1'),
  ('whole wheat tortilla', 'bakery', '🌮', 0.95, 'seed_v1'),
  ('whole wheat wrap', 'bakery', '🍞', 0.95, 'seed_v1'),
  ('wild rice', 'grain', '🍚', 0.95, 'seed_v1'),
  ('wine', 'alcohol', '🍷', 0.95, 'seed_v1'),
  ('worcestershire sauce', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('wrap', 'bakery', '🍞', 0.95, 'seed_v1'),
  ('yam', 'produce', '🥬', 0.95, 'seed_v1'),
  ('yeast', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('yellow onion', 'produce', '🧅', 0.95, 'seed_v1'),
  ('yogurt', 'dairy', '🥣', 0.95, 'seed_v1'),
  ('zaatar', 'pantry', '🥫', 0.95, 'seed_v1'),
  ('zip bag', 'household', '🧻', 0.95, 'seed_v1'),
  ('zucchini', 'produce', '🥬', 0.95, 'seed_v1')
on conflict (normalized_text) do update
set category = excluded.category,
    emoji = excluded.emoji,
    confidence = excluded.confidence,
    source = excluded.source,
    updated_at = now();
